"""Initial unified schema

Revision ID: 7d4b3424e102
Revises: 
Create Date: 2025-11-30 00:21:43.207813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = '7d4b3424e102'
down_revision: Union[str, Sequence[str], None] = 'z0enablepgvec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_documents_id'), 'finance_documents', ['id'], unique=False)
    op.create_table('marketing_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_documents_id'), 'marketing_documents', ['id'], unique=False)
    op.create_table('ops_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_documents_id'), 'ops_documents', ['id'], unique=False)
    op.create_table('tech_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_documents_id'), 'tech_documents', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('cfo_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfo_analyses_created_at'), 'cfo_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_cfo_analyses_id'), 'cfo_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_cfo_analyses_risk_level'), 'cfo_analyses', ['risk_level'], unique=False)
    op.create_index(op.f('ix_cfo_analyses_user_id'), 'cfo_analyses', ['user_id'], unique=False)
    op.create_table('cfo_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfo_chat_messages_id'), 'cfo_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_cfo_chat_messages_session_id'), 'cfo_chat_messages', ['session_id'], unique=False)
    op.create_table('cmo_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmo_analyses_created_at'), 'cmo_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_cmo_analyses_id'), 'cmo_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_cmo_analyses_risk_level'), 'cmo_analyses', ['risk_level'], unique=False)
    op.create_index(op.f('ix_cmo_analyses_user_id'), 'cmo_analyses', ['user_id'], unique=False)
    op.create_table('coo_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=False),
    sa.Column('priority_area', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coo_analyses_created_at'), 'coo_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_coo_analyses_id'), 'coo_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_coo_analyses_risk_level'), 'coo_analyses', ['risk_level'], unique=False)
    op.create_index(op.f('ix_coo_analyses_user_id'), 'coo_analyses', ['user_id'], unique=False)
    op.create_table('cto_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cto_analyses_created_at'), 'cto_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_cto_analyses_id'), 'cto_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_cto_analyses_risk_level'), 'cto_analyses', ['risk_level'], unique=False)
    op.create_index(op.f('ix_cto_analyses_user_id'), 'cto_analyses', ['user_id'], unique=False)
    op.create_table('cto_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cto_chat_messages_created_at'), 'cto_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_cto_chat_messages_id'), 'cto_chat_messages', ['id'], unique=False)
    op.create_table('coo_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['coo_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coo_chat_messages_id'), 'coo_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_coo_chat_messages_session_id'), 'coo_chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coo_chat_messages_session_id'), table_name='coo_chat_messages')
    op.drop_index(op.f('ix_coo_chat_messages_id'), table_name='coo_chat_messages')
    op.drop_table('coo_chat_messages')
    op.drop_index(op.f('ix_cto_chat_messages_id'), table_name='cto_chat_messages')
    op.drop_index(op.f('ix_cto_chat_messages_created_at'), table_name='cto_chat_messages')
    op.drop_table('cto_chat_messages')
    op.drop_index(op.f('ix_cto_analyses_user_id'), table_name='cto_analyses')
    op.drop_index(op.f('ix_cto_analyses_risk_level'), table_name='cto_analyses')
    op.drop_index(op.f('ix_cto_analyses_id'), table_name='cto_analyses')
    op.drop_index(op.f('ix_cto_analyses_created_at'), table_name='cto_analyses')
    op.drop_table('cto_analyses')
    op.drop_index(op.f('ix_coo_analyses_user_id'), table_name='coo_analyses')
    op.drop_index(op.f('ix_coo_analyses_risk_level'), table_name='coo_analyses')
    op.drop_index(op.f('ix_coo_analyses_id'), table_name='coo_analyses')
    op.drop_index(op.f('ix_coo_analyses_created_at'), table_name='coo_analyses')
    op.drop_table('coo_analyses')
    op.drop_index(op.f('ix_cmo_analyses_user_id'), table_name='cmo_analyses')
    op.drop_index(op.f('ix_cmo_analyses_risk_level'), table_name='cmo_analyses')
    op.drop_index(op.f('ix_cmo_analyses_id'), table_name='cmo_analyses')
    op.drop_index(op.f('ix_cmo_analyses_created_at'), table_name='cmo_analyses')
    op.drop_table('cmo_analyses')
    op.drop_index(op.f('ix_cfo_chat_messages_session_id'), table_name='cfo_chat_messages')
    op.drop_index(op.f('ix_cfo_chat_messages_id'), table_name='cfo_chat_messages')
    op.drop_table('cfo_chat_messages')
    op.drop_index(op.f('ix_cfo_analyses_user_id'), table_name='cfo_analyses')
    op.drop_index(op.f('ix_cfo_analyses_risk_level'), table_name='cfo_analyses')
    op.drop_index(op.f('ix_cfo_analyses_id'), table_name='cfo_analyses')
    op.drop_index(op.f('ix_cfo_analyses_created_at'), table_name='cfo_analyses')
    op.drop_table('cfo_analyses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tech_documents_id'), table_name='tech_documents')
    op.drop_table('tech_documents')
    op.drop_index(op.f('ix_ops_documents_id'), table_name='ops_documents')
    op.drop_table('ops_documents')
    op.drop_index(op.f('ix_marketing_documents_id'), table_name='marketing_documents')
    op.drop_table('marketing_documents')
    op.drop_index(op.f('ix_finance_documents_id'), table_name='finance_documents')
    op.drop_table('finance_documents')
    # ### end Alembic commands ###
