/**
 * Constants for conversational intake: countries, sectors, org size, role labels.
 */

import type { ImpactCategoryId, MetricFocusArea, Role } from "./intake-types";

/** Full list of countries (ISO 3166-1 alpha-2), alphabetically sorted by label. Used in StepIdentity and StepInvestorProfile. */
export const INTAKE_COUNTRIES: { value: string; label: string }[] = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brazil" },
  { value: "BN", label: "Brunei Darussalam" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CV", label: "Cabo Verde" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo" },
  { value: "CD", label: "Congo, Democratic Republic of the" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Côte d'Ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czechia" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Greece" },
  { value: "GD", label: "Grenada" },
  { value: "GT", label: "Guatemala" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hong Kong" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran, Islamic Republic of" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "KP", label: "Korea, Democratic People's Republic of" },
  { value: "KR", label: "Korea, Republic of" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Lao People's Democratic Republic" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MO", label: "Macao" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia, Federated States of" },
  { value: "MD", label: "Moldova, Republic of" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands, Kingdom of the" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "MK", label: "North Macedonia" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestine, State of" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russian Federation" },
  { value: "RW", label: "Rwanda" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "Sao Tome and Principe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syrian Arab Republic" },
  { value: "TW", label: "Taiwan, Province of China" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania, United Republic of" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" },
  { value: "TG", label: "Togo" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Türkiye" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VE", label: "Venezuela, Bolivarian Republic of" },
  { value: "VN", label: "Viet Nam" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
  { value: "other", label: "Other" },
];

export const INTAKE_SECTORS: { value: string; label: string }[] = [
  { value: "retail", label: "Retail" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "services", label: "Services" },
  { value: "tech", label: "Technology" },
  { value: "f&b", label: "Food & Beverage" },
  { value: "healthcare", label: "Healthcare" },
  { value: "other", label: "Other" },
];

export const ORG_SIZE_BANDS: { value: string; label: string }[] = [
  { value: "solo", label: "Just me" },
  { value: "2-10", label: "2–10" },
  { value: "11-50", label: "11–50" },
  { value: "51-200", label: "51–200" },
  { value: "200+", label: "200+" },
];

export const ROLE_OPTIONS: { value: Role; label: string; description: string }[] = [
  {
    value: "msme_owner",
    label: "MSME Owner / Operator",
    description: "Running an established small or medium business (retail, services, manufacturing, etc.).",
  },
  {
    value: "startup_founder",
    label: "Startup Founder",
    description: "Building a new venture (pre-seed to scale-up), often tech-enabled or high-growth.",
  },
  {
    value: "social_enterprise_leader",
    label: "Social Enterprise Leader",
    description: "Running a business or organization with a clear social or environmental mission that you report to funders or partners.",
  },
  {
    value: "aspiring_entrepreneur",
    label: "Aspiring Entrepreneur",
    description: "Idea or validation stage, not yet operating.",
  },
  {
    value: "impact_investor",
    label: "Impact Investor / Capital Partner",
    description: "Investors and funders seeking portfolio-level diagnostics, due diligence, and impact reporting.",
  },
];

/** Founder path: primary area affected. */
export const PRIMARY_AREA_OPTIONS = [
  { value: "finance", label: "Finance / cash" },
  { value: "operations", label: "Operations / process" },
  { value: "growth", label: "Growth / demand" },
  { value: "tech", label: "Technology / systems" },
  { value: "multiple", label: "Multiple / not sure" },
];

/** Founder path: business stage dropdown. */
export const BUSINESS_STAGE_OPTIONS = [
  { value: "pre_revenue", label: "Pre-revenue / validating" },
  { value: "early_revenue", label: "Early revenue (1–3 years)" },
  { value: "scaling", label: "Scaling (3–5 years)" },
  { value: "growth", label: "Growth (5+ years)" },
  { value: "other", label: "Other" },
];

/** Founder path: primary theme. */
export const PRIMARY_THEME_OPTIONS = [
  { value: "cash_flow", label: "Cash flow" },
  { value: "hiring", label: "Hiring / team" },
  { value: "fundraising", label: "Fundraising" },
  { value: "product_market", label: "Product-market fit" },
  { value: "supply_chain", label: "Supply chain" },
  { value: "other", label: "Other" },
];

/** Founder path: most urgent. */
export const MOST_URGENT_OPTIONS = [
  { value: "survive_cash", label: "Cash / runway" },
  { value: "fix_ops", label: "Operations / process" },
  { value: "grow_demand", label: "Growth / demand" },
  { value: "tech", label: "Technology / systems" },
];

/** Founder path: diagnostic goal. */
export const DIAGNOSTIC_GOAL_OPTIONS = [
  { value: "improve_cash_flow", label: "Improve cash flow" },
  { value: "scale_operations", label: "Scale operations" },
  { value: "investor_ready", label: "Get investor ready" },
  { value: "", label: "Just clarify and plan" },
];

/** Founder path: decision horizon. */
export const DECISION_HORIZON_OPTIONS = [
  { value: "1_month", label: "1 month" },
  { value: "3_months", label: "3 months" },
  { value: "6_months", label: "6 months" },
  { value: "12_months", label: "12 months" },
  { value: "other", label: "Other" },
];

/** MSME path: challenge options (value matches legacy). */
export const MSME_CHALLENGE_OPTIONS = [
  { value: "cash_tight", label: "Cash feels tight or unpredictable" },
  { value: "customers_late", label: "Customers are paying late or not paying" },
  { value: "sales_declining", label: "Sales are declining or unstable" },
  { value: "costs_rising", label: "Costs are rising faster than revenue" },
  { value: "decisions_on_me", label: "Too many decisions depend on me" },
  { value: "ops_messy", label: "Operations feel messy or fragile" },
  { value: "not_sure", label: "I'm not sure; it's complicated" },
];

/** MSME path: primary focus. */
export const MSME_PRIMARY_FOCUS_OPTIONS = [
  { value: "cfo", label: "Finance / cash" },
  { value: "cmo", label: "Growth / marketing" },
  { value: "coo", label: "Operations" },
  { value: "cto", label: "Technology" },
];

/** 8 Universal Impact Categories (social enterprise add-on). */
export const IMPACT_CATEGORIES: { value: ImpactCategoryId; label: string }[] = [
  { value: "livelihoods_income", label: "Livelihoods & Income" },
  { value: "education_skills", label: "Education & Skills" },
  { value: "health_wellbeing", label: "Health & Wellbeing" },
  { value: "environment_climate", label: "Environment & Climate" },
  { value: "financial_inclusion", label: "Financial Inclusion" },
  { value: "gender_inclusion", label: "Gender & Inclusion" },
  { value: "community_development", label: "Community Development" },
  { value: "governance_rights", label: "Governance & Rights" },
];

/** Metric focus areas (social enterprise). */
export const METRIC_FOCUS_AREAS: { value: MetricFocusArea; label: string }[] = [
  { value: "reach", label: "Reach (beneficiaries, geography)" },
  { value: "jobs_and_income", label: "Jobs & income" },
  { value: "education", label: "Education" },
  { value: "health", label: "Health" },
  { value: "environment", label: "Environment" },
  { value: "financial_inclusion", label: "Financial inclusion" },
  { value: "gender_inclusion", label: "Gender & inclusion" },
];

/** Investor: portfolio stage. */
export const PORTFOLIO_STAGE_OPTIONS = [
  { value: "evaluating_opportunities", label: "Evaluating opportunities" },
  { value: "active_portfolio", label: "Active portfolio" },
  { value: "reporting_phase", label: "Reporting phase" },
  { value: "mixed", label: "Mixed" },
];

/** Investor: primary needs from CLEAR. */
export const INVESTOR_NEED_OPTIONS = [
  { value: "due_diligence_support", label: "Due diligence support" },
  { value: "portfolio_monitoring", label: "Portfolio monitoring" },
  { value: "impact_measurement_and_reporting", label: "Impact measurement & reporting" },
  { value: "exit_and_realization_planning", label: "Exit & realization planning" },
];
